spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  application:
    name: hit-shot

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8
    check-template-location: true

  web:
    resources:
      add-mappings: false

bucket:
  token-count: 1000

client:
  slack:
    url: ${CLIENT_SLACK_URL}
